server:
  port: 8083

spring:
  datasource:
    username: admin
    password: TEST
    url: jdbc:mysql://scc.cm208wdfje8i.us-east-2.rds.amazonaws.com:3306/auth

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: bael-admin
      password: pass
    realmImportFile: baeldung-realm.json
