server:
  port: 8083

spring:
  datasource:
    username: sa
    password: admin
    url: jdbc:h2:mem:testdb

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: super-admin
      password: SomethingLong123!
    realmImportFile: baeldung-realm.json
